### ISSUE TITLE
How could I schedule the cron job to run only on day 1,3,5.  I tried multiple ways, but it always gives an error for what I tried.  1-5 works, but I need to be able to specify multiple days with gaps between.

### ISSUE THREAD

**Issue by jodymac** [agilord/cron#1]

**Comment by jodymac** [comment]
Thank you for replying  I've tried the following..  At the time I was testing it going off at 1:01 which worked just fine.  But can't figure out the days if I wanted days 1,3 & 5 to be the days it ran.

1.  cron.schedule(new Schedule.parse('1 13 1,3,5 * *'), () async { 

2. var days = [1,3,5]
cron.schedule(new Schedule.parse('1 13 $days * *'), () async {

**Comment by isoos** [comment]
The first issue you've mentioned: that was a type-cast bug that was hidden. The package needs some tests, and exactly for this reason. I've published version `0.2.1` to fix that.

The second issue however, is an issue of the input format:

```
final list = [1,3,5];
print('$list');
// prints [1, 2, 3]
```
notice the spaces between the numbers and the open and close `[` `]`. In effect, you are trying to parse `'1 13 [1, 3, 5] * *'` which is not a valid crontab entry.

**Comment by jodymac** [comment]
Awesome, thanks!

**Comment by jodymac** [comment]
Thank you for updating.  I think it is ignoring the day entry now.  If I leave the default asterisk, it works.  but if I put a number in, it won’t work.  ie 5 or 6.  I tried all the numbers too 1,2,3,4,5,6,7 and 0,1,2,3,4,5,6.  No crashing, but it won’t fire unless the day is *.  

Didn’t know if you wanted me to create a new issue, so I thought I’d try this.

Jody

**Comment by isoos** [comment]
@jodymac: can you please share the cron setup you are trying to make work? I think there is a chance that you are trying the wrong order, as the structure is the following:
`[minutes] [hours] [days] [months] [weekdays]`

If you set `1-7` to `[days]` it will trigger on the first 7 days on a given month, and today is the 25th, so it won't trigger anything. If you want to set it to trigger on Mon, Wed, Fri, then you need to do it in the last block.

**Comment by jodymac** [comment]
You are absolutely right, my formatting was wrong.  I was treating days as weekdays.  Sorry to bother you, I hate making stupid mistakes like that, especially after making sure I had dug info on the internet and thought I had it right.  I had mistakenly read it as I could specify days as either ints or by text name.  It’s completely clear after you wrote that.

Thank you for making the plugin, I’m testing it an app that schedules tasks for people.
