### ISSUE TITLE
How to Get call back every 5 seconds

### ISSUE THREAD

**Issue by AliEasy** [agilord/cron#14]
Hi
So I need to get call back every 5 seconds
How can I manage to do that?!

**Comment by isoos** [comment]
The `Schedule` constructor has `seconds` as a parameter:
https://pub.dev/documentation/cron/latest/cron/Schedule/Schedule.html
> " Can be one of `int`, `List<int>` or `String` or `null` (= match all)."

e.g. `seconds: '*/5'` should work

**Comment by AliEasy** [comment]
Thanks
Works like a charm
