### ISSUE TITLE
Background work not executing

### ISSUE THREAD

**Issue by hassanrehman01398** [agilord/cron#19]
Cron job is not working in background.I scheduled the

**Comment by isoos** [comment]
As described in issues #3, #6 and #7, this package is meant for server-side apps.

**Comment by AbhijithKonnayil** [comment]
If this is only for server-side then why the tag is for Android and iOS

**Comment by AbhijithKonnayil** [comment]
> As described in issues #3, #6 and #7, this package is meant for server-side apps.

If this is only for server-side then why the tag is for Android and iOS

**Comment by isoos** [comment]
> If this is only for server-side then why the tag is for Android and iOS

Tagging happens on pub.dev automatically - if a package can be used on a platform, it will receive a tag. Whether it is useful to use it on a platform - is another matter. If you care only about frontend-thread timers, it is still useful though...

**Comment by bahman2000** [comment]
@JoniJohn  I'm agree with you. I spent some time with the cron timing syntax. I just realized that this package is meant for server-side apps! Not for client-side apps!

**Comment by isoos** [comment]
@RyanParkGH: please report your results, including which platforms you were running. I think Android is really aggressive nowadays to force-sleep applications that are in the background, and you would need to go through a few menu in the settings to enable it for app-by-app.

**Comment by RyanParkGH** [comment]
> @RyanParkGH: please report your results, including which platforms you were running. I think Android is really aggressive nowadays to force-sleep applications that are in the background, and you would need to go through a few menu in the settings to enable it for app-by-app.

Just completed testing, 8 hours of running a Cron that created a timestamp on a supabase instance every minute. I was using Flutter Web for this test, which should be the most fickle platform, I would expect Android to be more reliable given the limitations of PWAs.

Anyway, the test was a success, timestamps continued to be created across the entire 8 hours.
