### ISSUE TITLE
Cron is Best in the Field, Why not we Try to Enhance Cron to Background-Processes

### ISSUE THREAD

**Issue by madd-project** [agilord/cron#20]
Cron is doing the most different and new thing, Thanks to the @agilord
There is no other software, better than Cron, in the pub. dev.

People are coming to use `cron` as for background processes, 
People are loving the foreground processes of the cron,
I am a developer who loves to work with cron and its easy-to-use interface.
People are giving the signal, that they want background processes as soon, because there are not better packages that are efficient like cron, 

Why Don't we develop Cron to background Processes,
Just ask ourselves, for how long we are gonna say Cron as Server-side Development Package?

@agilord has developed a great technology and it is the best in the field, 
By using Different Packages that already exist, ex, work manager, move_to_background, flutter_background we can achieve this easily.

People are giving the signal, that they want background processes as soon, because there are not better packages that are efficient like cron,

**Comment by mehransahandi** [comment]
indeed this will be the biggest update to cron

**Comment by bahman2000** [comment]
@madd-project @mehransahandi We don't need to wait for Cron to be updated. It is enough to use two packages together:

flutter_background_service + cron

**Comment by isoos** [comment]
Please consider using `flutter_background_service` (or similar) for this use case, as @bahman2000 suggested.
I don't plan to extend the scope of this package to also handle mobile.
