### ISSUE TITLE
Support better exception handling on parse

### ISSUE THREAD

**Issue by bsutton** [agilord/cron#29]
Currently when parsing a schedule the cron library throws an Exception when a parse fails.

This is difficult to catch as it is too generic.

Can we replace this with a specific exception such as:

ScheduleParseException
ParseException

or maybe FormatException - not my preferred as it is used by other functions.

**Comment by isoos** [comment]
I'm down for `ScheduleParseException extends/implements FormatException`. Are you interested creating a PR for it?

**Comment by bsutton** [comment]
I'm struggling for time at the moment so I'm going to have to say no.

**Comment by myConsciousness** [comment]
I created the PR myself as it appears it has not been maintained for some time.

Please check back when you have time @isoos :)
