### ISSUE TITLE
Maybe the package structure should be refactored?

### ISSUE THREAD

**Issue by myConsciousness** [agilord/cron#35]
Hi amazing developers,

The functionality of this package seems complete, but the structure of the package appears somewhat complex.
So shouldn't it be refactored to the extent that there are no destructive changes?

For example, most implementations are currently in `cron.dart` under the `lib` folder, but these should be splitted per class and stored in `lib/src`.
This alone would make the package much more maintainable.

Thank you.

**Comment by myConsciousness** [comment]
However, thinking about it, I have a feeling that this would not be effective because the commit history would be lost 🤔

**Comment by isoos** [comment]
>  but these should be splitted per class and stored in lib/src.

`lib/cron.dart` is around 200 lines, I'm not sure if it needs to be refactored, but if you feel strongly about it, I don't mind.

**Comment by myConsciousness** [comment]
I've given it some thought and I think a major refactoring may not be necessary, I mean it is possible but I felt it was not cost-effective 🤔

Anyway I improve #34 :)
