### ISSUE TITLE
How to close instance of cron to create a new one

### ISSUE THREAD

**Issue by jodymac** [agilord/cron#4]
I want to give my users the ability to set the cron job to run at their day and time specifications.  I have that working properly, but I'm left with multiple scheduled cron jobs.  I would like to invalidate the previous cron job so that it doesn't run anymore at all.  I had hoped that calling close() would kill the old process, but, as stated in the docs, it only prevents that instance from getting new scheduling.

I have a cronjob class that has the variable final cron = new Cron()  and I schedule from another class.

How can I completely kill any previous scheduling so I can start fresh for scheduling?

**Comment by isoos** [comment]
Disclaimer: I have no idea how reliable this is on a mobile app, and what happens if the device reboots or something else happens.

On the specific issue: would it help if `schedule(Schedule schedule, Task task)` would return a `ScheduledTask` like this?

```
abstract class ScheduledTask {
  Schedule get schedule;
  Future cancel();
}
```
The cancel would yield immediately, or if the task is currently running, the future will complete when the task completes.

**Comment by jodymac** [comment]
That is exactly what I am looking for.  This will allow me to have the user change automatic report generation to another time.

My experience so far has been that the cron job will cancel on app termination/device restart.  It will continue to run when the app moves to the background, but only until the app times out in the background.  Then the cron job will cancel at that point too.  Right now I detect when the app becomes active and reinstate the cron at that point, but that is not the ideal solution.  I'm digging into isolates and other plugins for background running right now.

BTW, I'm exclusively running on ios and ios simulator currently for what I mentioned above.

**Comment by isoos** [comment]
I've released 0.2.2 to support that. Let me know if you need further API changes.

**Comment by jodymac** [comment]
Thank you very much for the quick turnaround time!  Completely unexpected and appreciated!

**Comment by jodymac** [comment]
I haven’t been able to successfully cancel my cron job yet with the updated package.

Could you please show me how you would cancel the below cron job.

I currently create dynamically with the user selecting minutes, hours and days ...

var cron = Cron();

  cron.schedule(new Schedule.parse('$minutes $hours * * $weekdays'), () async {
    scheduleAction();  //where I run my actions.
  });

Thank you in advance!

**Comment by jodymac** [comment]
Thank you again!

**Comment by jodymac** [comment]
This works as expected when run as listed.  However, the problem I’m running into is that I’m having trouble for my particular use case.  I probably should have explained my use case at the time you suggested the cancel option, but apparently I jumped before looking.

I have one screen that allows the user to set a time of day and set which days to run. ('$minutes $hours * * $weekdays’).  My use case is that I want to give the user the option to change when the cron job runs.  This could occur….
1.  multiple times the first day they have the app as they test the results to see how it works.
2.  They set the cronJob on setup but realize they’d prefer to have it another time.
3.  Months down the road, they decide they want a different time or to eliminate or add days.

In each of these, it is not known if the cron job they set is the final one, so I can’t cancel after run.  I only need to cancel once they try to set the change, otherwise the cron job need to run.

So I need to...
1. get a reference to the existing cron job.
2. cancel that existing cron job.
3. schedule a new cron job.

**Comment by isoos** [comment]
I'd suggest the following:

```
final cron = Cron();
final schedules = <String, ScheduledTask>{};

final st = cron.schedule(new Schedule.parse('$minutes $hours * * $weekdays'), () async {
    scheduleAction();  //where I run my actions.
  });
schedules['id1'] = st;

// ....
// sometime later

final st = schedules['id1'];
await st.cancel();

```

**Comment by jodymac** [comment]
Excellent!  Works Perfectly!!!

Thank you again.
