### ISSUE TITLE
Idea to Add IsRunning method 

### ISSUE THREAD

**Issue by TOMER628** [agilord/cron#47]
hi.

thank you for your package help me a lot.

can you add/release please new method to check if isRunning ?

regards,
Tomer.

**Comment by isoos** [comment]
@TOMER628: I'm happy to take PRs if you wanted to contribute. What would be the use case for the method / what would be the condition when it returns true/false?

**Comment by TOMER628** [comment]
if exist any cronSchedule return true

**Comment by francescovallone** [comment]
I think we can close this issue @isoos. Thank you so much!

**Comment by isoos** [comment]
Thanks for the notice (and the PR), closing.
